ALTER TABLE posts ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE posts ALTER COLUMN created_at SET DEFAULT now();

ALTER TABLE posts ALTER COLUMN updated_at SET NOT NULL;
ALTER TABLE posts ALTER COLUMN updated_at SET DEFAULT now();

ALTER TABLE users ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE users ALTER COLUMN created_at SET DEFAULT now();

ALTER TABLE users ALTER COLUMN updated_at SET NOT NULL;
ALTER TABLE users ALTER COLUMN updated_at SET DEFAULT now();